DROP TABLE IF EXISTS INTEGRA.USUARIO;
DROP TABLE IF EXISTS INTEGRA.CLIENTE;
DROP TABLE IF EXISTS INTEGRA.GRUPO;

CREATE TABLE INTEGRA.USUARIO (
  id INTEGER(11) PRIMARY KEY,
  nome VARCHAR(100) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  usuario VARCHAR(100) DEFAULT NULL,
  senha VARCHAR(100) DEFAULT NULL,
  status INTEGER(11) DEFAULT NULL,
  data_criacao date DEFAULT NULL,
  cliente_id INTEGER(11) KEY);
  

CREATE TABLE INTEGRA.CLIENTE (
  id INTEGER(11) PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  ativo INTEGER(1) DEFAULT '1'); 
  

CREATE TABLE INTEGRA.GRUPO (
  id INTEGER(11) PRIMARY KEY,
  nome VARCHAR(100) DEFAULT NULL) 

